// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

type CreateUserPayload struct {
	User   *User    `json:"user"`
	Errors []*Error `json:"errors,omitempty"`
}

type DeleteUserPayload struct {
	Success bool     `json:"success"`
	Errors  []*Error `json:"errors,omitempty"`
}

type Error struct {
	Message string  `json:"message"`
	Field   *string `json:"field,omitempty"`
	Code    *string `json:"code,omitempty"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Query struct {
}

type UpdateUserInput struct {
	Email *string `json:"email,omitempty"`
	Name  *string `json:"name,omitempty"`
}

type UpdateUserPayload struct {
	User   *User    `json:"user"`
	Errors []*Error `json:"errors,omitempty"`
}

type User struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type UserConnection struct {
	Edges    []*UserEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type UserEdge struct {
	Node   *User  `json:"node"`
	Cursor string `json:"cursor"`
}
