// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ApproveLeaveInput struct {
	ApprovedBy string `json:"approvedBy"`
}

type ApproveLeavePayload struct {
	Leave  *Leave   `json:"leave"`
	Errors []*Error `json:"errors,omitempty"`
}

type CancelLeavePayload struct {
	Leave  *Leave   `json:"leave"`
	Errors []*Error `json:"errors,omitempty"`
}

type CreateDepartmentInput struct {
	Name        string  `json:"name"`
	Description string  `json:"description"`
	ManagerID   *string `json:"managerId,omitempty"`
}

type CreateDepartmentPayload struct {
	Department *Department `json:"department"`
	Errors     []*Error    `json:"errors,omitempty"`
}

type CreateEmployeeInput struct {
	UserID       string  `json:"userId"`
	EmployeeCode string  `json:"employeeCode"`
	Department   string  `json:"department"`
	Position     string  `json:"position"`
	HireDate     string  `json:"hireDate"`
	Salary       float64 `json:"salary"`
	Status       string  `json:"status"`
}

type CreateEmployeePayload struct {
	Employee *Employee `json:"employee"`
	Errors   []*Error  `json:"errors,omitempty"`
}

type CreateLeaveInput struct {
	EmployeeID string `json:"employeeId"`
	LeaveType  string `json:"leaveType"`
	StartDate  string `json:"startDate"`
	EndDate    string `json:"endDate"`
	Reason     string `json:"reason"`
}

type CreateLeavePayload struct {
	Leave  *Leave   `json:"leave"`
	Errors []*Error `json:"errors,omitempty"`
}

type CreatePositionInput struct {
	Title        string  `json:"title"`
	Description  string  `json:"description"`
	DepartmentID *string `json:"departmentId,omitempty"`
	Requirements string  `json:"requirements"`
	MinSalary    float64 `json:"minSalary"`
	MaxSalary    float64 `json:"maxSalary"`
}

type CreatePositionPayload struct {
	Position *Position `json:"position"`
	Errors   []*Error  `json:"errors,omitempty"`
}

type CreateUserInput struct {
	Email string `json:"email"`
	Name  string `json:"name"`
}

type CreateUserPayload struct {
	User   *User    `json:"user"`
	Errors []*Error `json:"errors,omitempty"`
}

type DeleteDepartmentPayload struct {
	Success bool     `json:"success"`
	Errors  []*Error `json:"errors,omitempty"`
}

type DeleteEmployeePayload struct {
	Success bool     `json:"success"`
	Errors  []*Error `json:"errors,omitempty"`
}

type DeleteLeavePayload struct {
	Success bool     `json:"success"`
	Errors  []*Error `json:"errors,omitempty"`
}

type DeletePositionPayload struct {
	Success bool     `json:"success"`
	Errors  []*Error `json:"errors,omitempty"`
}

type DeleteUserPayload struct {
	Success bool     `json:"success"`
	Errors  []*Error `json:"errors,omitempty"`
}

type Department struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	ManagerID   *string `json:"managerId,omitempty"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type DepartmentConnection struct {
	Edges    []*DepartmentEdge `json:"edges"`
	PageInfo *PageInfo         `json:"pageInfo"`
}

type DepartmentEdge struct {
	Node   *Department `json:"node"`
	Cursor string      `json:"cursor"`
}

type Employee struct {
	ID           string  `json:"id"`
	User         *User   `json:"user"`
	EmployeeCode string  `json:"employeeCode"`
	Department   string  `json:"department"`
	Position     string  `json:"position"`
	HireDate     string  `json:"hireDate"`
	Salary       float64 `json:"salary"`
	Status       string  `json:"status"`
	CreatedAt    string  `json:"createdAt"`
	UpdatedAt    string  `json:"updatedAt"`
}

type EmployeeConnection struct {
	Edges    []*EmployeeEdge `json:"edges"`
	PageInfo *PageInfo       `json:"pageInfo"`
}

type EmployeeEdge struct {
	Node   *Employee `json:"node"`
	Cursor string    `json:"cursor"`
}

type Error struct {
	Message string  `json:"message"`
	Field   *string `json:"field,omitempty"`
	Code    *string `json:"code,omitempty"`
}

type Leave struct {
	ID         string  `json:"id"`
	EmployeeID string  `json:"employeeId"`
	LeaveType  string  `json:"leaveType"`
	StartDate  string  `json:"startDate"`
	EndDate    string  `json:"endDate"`
	Reason     string  `json:"reason"`
	Status     string  `json:"status"`
	ApprovedBy *string `json:"approvedBy,omitempty"`
	ApprovedAt *string `json:"approvedAt,omitempty"`
	CreatedAt  string  `json:"createdAt"`
	UpdatedAt  string  `json:"updatedAt"`
}

type LeaveConnection struct {
	Edges    []*LeaveEdge `json:"edges"`
	PageInfo *PageInfo    `json:"pageInfo"`
}

type LeaveEdge struct {
	Node   *Leave `json:"node"`
	Cursor string `json:"cursor"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage     bool    `json:"hasNextPage"`
	HasPreviousPage bool    `json:"hasPreviousPage"`
	StartCursor     *string `json:"startCursor,omitempty"`
	EndCursor       *string `json:"endCursor,omitempty"`
}

type Position struct {
	ID           string  `json:"id"`
	Title        string  `json:"title"`
	Description  string  `json:"description"`
	DepartmentID *string `json:"departmentId,omitempty"`
	Requirements string  `json:"requirements"`
	MinSalary    float64 `json:"minSalary"`
	MaxSalary    float64 `json:"maxSalary"`
	CreatedAt    string  `json:"createdAt"`
	UpdatedAt    string  `json:"updatedAt"`
}

type PositionConnection struct {
	Edges    []*PositionEdge `json:"edges"`
	PageInfo *PageInfo       `json:"pageInfo"`
}

type PositionEdge struct {
	Node   *Position `json:"node"`
	Cursor string    `json:"cursor"`
}

type Query struct {
}

type RejectLeavePayload struct {
	Leave  *Leave   `json:"leave"`
	Errors []*Error `json:"errors,omitempty"`
}

type UpdateDepartmentInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	ManagerID   *string `json:"managerId,omitempty"`
}

type UpdateDepartmentPayload struct {
	Department *Department `json:"department"`
	Errors     []*Error    `json:"errors,omitempty"`
}

type UpdateEmployeeInput struct {
	EmployeeCode *string  `json:"employeeCode,omitempty"`
	Department   *string  `json:"department,omitempty"`
	Position     *string  `json:"position,omitempty"`
	HireDate     *string  `json:"hireDate,omitempty"`
	Salary       *float64 `json:"salary,omitempty"`
	Status       *string  `json:"status,omitempty"`
}

type UpdateEmployeePayload struct {
	Employee *Employee `json:"employee"`
	Errors   []*Error  `json:"errors,omitempty"`
}

type UpdateLeaveInput struct {
	LeaveType *string `json:"leaveType,omitempty"`
	StartDate *string `json:"startDate,omitempty"`
	EndDate   *string `json:"endDate,omitempty"`
	Reason    *string `json:"reason,omitempty"`
}

type UpdateLeavePayload struct {
	Leave  *Leave   `json:"leave"`
	Errors []*Error `json:"errors,omitempty"`
}

type UpdatePositionInput struct {
	Title        *string  `json:"title,omitempty"`
	Description  *string  `json:"description,omitempty"`
	DepartmentID *string  `json:"departmentId,omitempty"`
	Requirements *string  `json:"requirements,omitempty"`
	MinSalary    *float64 `json:"minSalary,omitempty"`
	MaxSalary    *float64 `json:"maxSalary,omitempty"`
}

type UpdatePositionPayload struct {
	Position *Position `json:"position"`
	Errors   []*Error  `json:"errors,omitempty"`
}

type UpdateUserInput struct {
	Email *string `json:"email,omitempty"`
	Name  *string `json:"name,omitempty"`
}

type UpdateUserPayload struct {
	User   *User    `json:"user"`
	Errors []*Error `json:"errors,omitempty"`
}

type User struct {
	ID        string `json:"id"`
	Email     string `json:"email"`
	Name      string `json:"name"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

type UserConnection struct {
	Edges    []*UserEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type UserEdge struct {
	Node   *User  `json:"node"`
	Cursor string `json:"cursor"`
}
