package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"fmt"
	"log"
	"strconv"
	"time"

	"github.com/captain-corgi/go-graphql-example/internal/hackernews/graph/model"
	"github.com/captain-corgi/go-graphql-example/internal/hackernews/links"
)

// CreateLink is the resolver for the createLink field.
func (r *mutationResolver) CreateLink(ctx context.Context, input model.NewLink) (*model.Link, error) {
	// Greeting
	timer := time.Now()
	log.Printf("CreateLink START")

	// Input models
	var (
		address = input.Address
		title   = input.Title
	)

	// Output model
	var (
		rs model.Link
	)

	// Do some business logic
	// Persist data
	var link links.Link
	link.Title = title
	link.Address = address
	linkId := link.Save(ctx)

	rs.Address = address
	rs.Title = title
	rs.ID = strconv.FormatInt(linkId, 10)
	rs.User = &model.User{
		Name: "Sample user",
	}

	// Return data
	defer log.Printf("CreateLink END within %dms", time.Duration(time.Since(timer).Milliseconds()))
	return &rs, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (string, error) {
	panic(fmt.Errorf("not implemented: CreateUser - createUser"))
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.Login) (string, error) {
	panic(fmt.Errorf("not implemented: Login - login"))
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input model.RefreshTokenInput) (string, error) {
	panic(fmt.Errorf("not implemented: RefreshToken - refreshToken"))
}

// Links is the resolver for the links field.
func (r *queryResolver) Links(ctx context.Context) ([]*model.Link, error) {
	// Greeting
	timer := time.Now()
	log.Printf("Links START")

	// Output models
	var (
		rsLinks = make([]*model.Link, 0)
	)

	// Do some business logic
	// Fetch data
	dbLinks := links.GetAll(ctx)
	for _, dbLink := range dbLinks {
		rsLinks = append(rsLinks, &model.Link{
			ID:      dbLink.ID,
			Title:   dbLink.Title,
			Address: dbLink.Address,
		})
	}

	// Return data
	defer log.Printf("Links END within %dms", time.Duration(time.Since(timer).Milliseconds()))
	return rsLinks, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
