package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"fmt"
	"log"
	"strconv"
	"time"

	"golang.org/x/sync/errgroup"

	"github.com/captain-corgi/go-graphql-example/internal/hackernews/graph/model"
	"github.com/captain-corgi/go-graphql-example/internal/hackernews/links"
	"github.com/captain-corgi/go-graphql-example/internal/hackernews/users"
	"github.com/captain-corgi/go-graphql-example/pkg/jwt"
)

// CreateLink is the resolver for the createLink field.
func (r *mutationResolver) CreateLink(ctx context.Context, input model.NewLink) (*model.Link, error) {
	// Greeting
	timer := time.Now()
	log.Printf("CreateLink START")

	// Input models
	var (
		address = input.Address
		title   = input.Title
	)

	// Output model
	var (
		rs model.Link
	)

	// Do some business logic
	// Persist data
	var link links.Link
	link.Title = title
	link.Address = address
	linkId := link.Save(ctx)

	rs.Address = address
	rs.Title = title
	rs.ID = strconv.FormatInt(linkId, 10)
	rs.User = &model.User{
		Name: "Sample user",
	}

	// Return data
	defer log.Printf("CreateLink END within %dms", time.Duration(time.Since(timer).Milliseconds()))
	return &rs, nil
}

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.NewUser) (string, error) {
	// Greeting
	timer := time.Now()
	log.Printf("CreateUser START")

	// Input models
	var (
		username = input.Username
		password = input.Password
	)
	// Output models
	var (
		user  users.User
		token string
	)

	// Do some logic business
	var (
		tokenChan = make(chan string)
	)
	wg, egCtx := errgroup.WithContext(ctx)
	// Create token
	wg.Go(func() error {
		token, err := jwt.GenerateToken(username)
		if err != nil {
			return err
		}
		tokenChan <- token
		return nil
	})

	// Persist data
	wg.Go(func() error {
		user.Username = username
		user.Password = password
		if affectedRows, err := user.Create(egCtx); err != nil {
			log.Printf("create user failed: %s", err)
			return err
		} else {
			log.Printf("%d rows affected", affectedRows)
		}
		return nil
	})

	// Wait response
	token = <-tokenChan
	if err := wg.Wait(); err != nil {
		return "", err
	}

	// Return data
	defer log.Printf("CreateUser END within %dms", time.Duration(time.Since(timer).Milliseconds()))
	return token, nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input model.Login) (string, error) {
	// Greeting
	timer := time.Now()
	log.Printf("Login START")

	var user users.User
	user.Username = input.Username
	user.Password = input.Password
	correct := user.Authenticate()
	if !correct {
		// 1
		defer log.Printf("Login END within %dms", time.Duration(time.Since(timer).Milliseconds()))
		return "", &users.WrongUsernameOrPasswordError{}
	}
	token, err := jwt.GenerateToken(user.Username)
	if err != nil {
		defer log.Printf("Login END within %dms", time.Duration(time.Since(timer).Milliseconds()))
		return "", err
	}

	// Return data
	defer log.Printf("Login END within %dms", time.Duration(time.Since(timer).Milliseconds()))
	return token, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input model.RefreshTokenInput) (string, error) {
	// Greeting
	timer := time.Now()
	log.Printf("RefreshToken START")

	username, err := jwt.ParseToken(input.Token)
	if err != nil {
		defer log.Printf("RefreshToken END within %dms", time.Duration(time.Since(timer).Milliseconds()))
		return "", fmt.Errorf("access denied")
	}
	token, err := jwt.GenerateToken(username)
	if err != nil {
		defer log.Printf("RefreshToken END within %dms", time.Duration(time.Since(timer).Milliseconds()))
		return "", err
	}
	// Return data
	defer log.Printf("RefreshToken END within %dms", time.Duration(time.Since(timer).Milliseconds()))
	return token, nil
}

// Links is the resolver for the links field.
func (r *queryResolver) Links(ctx context.Context) ([]*model.Link, error) {
	// Greeting
	timer := time.Now()
	log.Printf("Links START")

	// Output models
	var (
		rsLinks = make([]*model.Link, 0)
	)

	// Do some business logic
	// Fetch data
	dbLinks := links.GetAll(ctx)
	for _, dbLink := range dbLinks {
		rsLinks = append(rsLinks, &model.Link{
			ID:      dbLink.ID,
			Title:   dbLink.Title,
			Address: dbLink.Address,
		})
	}

	// Return data
	defer log.Printf("Links END within %dms", time.Duration(time.Since(timer).Milliseconds()))
	return rsLinks, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
