server:
  name: "go-graphql-example"
  port: "8080"
  read_timeout: "30s"
  write_timeout: "30s"
  idle_timeout: "120s"

database:
  url: "postgres://postgres:postgres@localhost:5432/graphql_service?sslmode=disable"
  max_open_conns: 10
  max_idle_conns: 2
  conn_max_lifetime: "5m"
  conn_max_idle_time: "5m"

logging:
  level: "debug"
  format: "text"

auth:
  jwt_secret: "dev-secret-key-32-chars-minimum-length-required"
  access_token_ttl: "15m"
  refresh_token_ttl: "24h"